# Generated by Django 5.1 on 2026-06-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
                'indexes': [models.Index(fields=['user_id'], name='account_use_user_id_c25fcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdministratorAdmin',
            fields=[
                ('admin_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'administrator_admin',
                'indexes': [models.Index(fields=['admin_id'], name='administrat_admin_i_f786bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
                'indexes': [models.Index(fields=['category_id'], name='shopping_ca_categor_061553_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='メーカー名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommended', models.BooleanField(default=False, max_length=1, verbose_name='オススメ')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.shoppingcategory', verbose_name='カテゴリID')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItemsIncart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.shoppingitem', verbose_name='商品ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.accountuser', verbose_name='会員ID')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.accountuser', verbose_name='注文者')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchaseDetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文詳細ID')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.shoppingitem', verbose_name='商品ID')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_site.shoppingpurchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['item_id'], name='shopping_it_item_id_8b7543_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingpurchase',
            index=models.Index(fields=['purchase_id'], name='shopping_pu_purchas_4abb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingpurchasedetail',
            index=models.Index(fields=['purchase_detail_id'], name='shopping_pu_purchas_84a25d_idx'),
        ),
    ]
